language: php
php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS pencms;" -uroot; fi
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer update --prefer-source --no-interaction --dev
  - php artisan migrate --force
  - php artisan db:seed

script:
  - phpunit
